services:
  postgres:
    image: postgres:latest
    container_name: lab-2-tools-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - configuration-service-network
    
  mypostgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5100:5432"
  
  configuration-service:
    image: ghcr.io/is-csms-y26/lab-2-tools:master
    platform: linux/amd64
    container_name: configuration-service
    networks:
      - configuration-service-network
    depends_on:
      - postgres
    ports:
      - '8081:8080'
    environment:
      Persistence__Postgres__Host: postgres

networks:
  configuration-service-network:
    driver: bridge